# These are supported funding model platforms

github: [octocat, surftocat]
patreon: catafest
ko_fi: catalingeorgefestila
custom: ["https://www.paypal.com/paypalme/catafest", https://sites.google.com/view/festila-george-catalin]
